// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/icons/close.svg"
    | "/icons/email.svg"
    | "/icons/github.svg"
    | "/icons/icon_128.png"
    | "/icons/icon_16.png"
    | "/icons/icon_48.png"
    | "/icons/settings.svg"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
